Repository fragforce/fragforce.org, pull requests merged in 2020-05, with the labels that each got.

#225 Rtmper
  ffstream/models.py
  ffstream/views.py
Labels: bug

#226 Missed Migration
  ffstream/migrations/0001_initial.py
Labels: bug

#227 Added admin UI
  ffstream/admin.py
Labels: enhancement

#232 Adding playback linking
  ffstream/urls.py
  ffstream/views.py
Labels: enhancement

#233 Adding playback linking based on name rather than key id
  ffstream/views.py
Labels: enhancement

#235 Fixed key => id for Key model
  ffstream/views.py
Labels: bug

#237 fixed url
  ffstream/migrations/0002_auto_20200517_1920.py
  ffstream/urls.py
Labels: bug

#239 Adding dash
  ffstream/templates/ffstream/view.html
Labels: enhancement

#240 Fixed POST vs GET
  ffstream/views.py
Labels: bug

#241 Removed force loop
  ffstream/views.py
Labels: bug

#242 Fixed key naming
  ffstream/views.py
Labels: bug

#245 Adding width
  ffstream/templates/ffstream/view.html
Labels: enhancement

#244 Getting UI Working
  ffstream/migrations/0002_auto_20200517_1920.py
  ffstream/models.py
  ffstream/templates/ffstream/view.html
  ffstream/urls.py
  ffstream/views.py
Labels: bug, enhancement

#246 Fixed Size & Default To Muted
  ffstream/templates/ffstream/view.html
Labels: enhancement

#247 Adding setting for stream
  fforg/settings.py
  ffstream/models.py
Labels: enhancement

#248 Fixing size and admin listing
  ffstream/models.py
  ffstream/templates/ffstream/view.html
Labels: bug, enhancement

#249 Added view for playing a stream
  ffstream/urls.py
  ffstream/views.py
Labels: enhancement

#250 Updated stream view with list of active keys
  ffstream/models.py
  ffstream/templates/ffstream/view.html
  ffstream/urls.py
  ffstream/views.py
Labels: bug, enhancement

#251 Fixed redirect
  ffstream/views.py
Labels: bug

#252 Better View UI
  fforg/settings.py
  ffstream/models.py
  ffstream/templates/ffstream/view.html
  ffstream/urls.py
  ffstream/views.py
Labels: bug, enhancement

#253 Making Stream View Blockier
  ffstream/templates/ffstream/view.html
Labels: bug

#254 Reducing size of cards
  ffstream/templates/ffstream/view.html
Labels: enhancement
