Repository fragforce/fragforce.org, pull requests merged in 2022-05, with the labels that each got.

#465 Tweak donations code to remove more edge cases
  ffdonations/tasks/donations.py
  ffdonations/tasks/sender.py
Labels: bug

#467 Piplock update
  Pipfile
  Pipfile.lock
Labels: enhancement

#468 A few
  ffdonations/tasks/participants.py
  ffdonations/tasks/tiltify/campaigns.py
  ffdonations/tasks/tiltify/donations.py
  fforg/settings.py
Labels: bug

#469 Bobblehead
  Procfile
  ffdonations/tasks/sender.py
  ffdonations/tasks/teams.py
  ffdonations/utils.py
  ffsite/views/static.py
Labels: bug, enhancement

#470 Update master from dev
  Pipfile
  Pipfile.lock
  Procfile
  ffdonations/tasks/participants.py
  ffdonations/tasks/sender.py
  ffdonations/tasks/teams.py
  ffdonations/tasks/tiltify/campaigns.py
  ffdonations/tasks/tiltify/donations.py
  ffdonations/utils.py
  fforg/settings.py
  ffsite/views/static.py
Labels: bug, enhancement
