Repository fragforce/fragforce.org, pull requests merged in 2023-04, with the labels that each got.

#571 Update master from dev
  .gitignore
  Dockerfile
  Pipfile.lock
  README.md
  dev/ffsfdc.sql
  dev/init.sh
  docker-compose.yml
  env.sample
  extralifeapi/base.py
  extralifeapi/teams.py
  ffdonations/tasks/donations.py
  ffdonations/tasks/teams.py
  ffdonations/utils.py
  ffdonations/views/donations.py
  fforg/settings.py
  ffsite/templates/ff/events/event.html
  ffsite/templates/ff/events/index.html
  ffsite/templates/ff/events/upcoming.html
  ffsite/templates/ff/sites/site.html
  ffsite/templatetags/fftz.py
Labels: bug, enhancement, dependencies

#577 Fix timeouts for extra life api
  fforg/settings.py
Labels: bug

#579 Fix donation doughnut
  ffdonations/utils.py
Labels: bug

#584 Update prod - fix latest donation
  ffdonations/views/donations.py
Labels: bug

#585 Format All The Things
  ffdonations/migrations/0024_auto_20210114_0258.py
  ffdonations/migrations/0025_auto_20210114_0302.py
  ffdonations/migrations/0026_donationmodel_tracking.py
  ffdonations/models.py
  ffdonations/tasks/__init__.py
  ffdonations/tasks/donations.py
  ffdonations/tasks/participants.py
  ffdonations/tasks/sender.py
  ffdonations/utils.py
  ffdonations/views/donations.py
  ffdonations/views/participants.py
  ffdonations/views/stats.py
  ffdonations/views/teams.py
  ffdonations/views/testing.py
  fforg/rdbs.py
  fforg/settings.py
  ffsite/ctx.py
  ffsite/static/ffsite/images/childsplay_logo.jpg
  ffsite/static/ffsite/images/combined.jpg
  ffsite/static/ffsite/images/devops.jpg
  ffsite/static/ffsite/images/minecraft.jpg
  ffsite/utils.py
  ffsite/views/events.py
  ffstream/admin.py
  ffstream/migrations/0005_key_livestream.py
  ffstream/models.py
  ffstream/views.py
Labels: enhancement
